# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pr:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build_Backend
    displayName: Build Backend
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Backend
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/backend/Dockerfile.prod'
        tags: |
          $(tag)

  - job: Build_Frontend
    displayName: Build Frontend
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Frontend
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/frontend/Dockerfile.prod'
        tags: |
          $(tag)

- stage: Test
  displayName: Test
  jobs:  
  - job: Test_Backend
    displayName: Test Backend
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CmdLine@2
      displayName: Install dependencies
      inputs:
        script: |
          npm install --only=dev
          npm install mkdirp
          sudo npm install -g newman
        workingDirectory: '$(Build.SourcesDirectory)/backend'
    - task: CmdLine@2
      displayName: Backend Lint
      inputs:
        script: |
          npm run lint
        workingDirectory: '$(Build.SourcesDirectory)/backend'

    - task: CmdLine@2
      displayName: Backend Format
      inputs:
        script: |
          npm run format
        workingDirectory: '$(Build.SourcesDirectory)/backend'

    - task: CmdLine@2
      displayName: Backend Test Api
      inputs:
        script: |
          docker build . -t ci
          docker run -d -p 80:5000 ci
          sleep 5
          npm run test
        workingDirectory: '$(Build.SourcesDirectory)/backend'

  - job: Test_Frontend
    displayName: Test Frontend
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CmdLine@2
      displayName: Install dependencies
      inputs:
        script: |
          npm install --only=dev
          npm install mkdirp
        workingDirectory: '$(Build.SourcesDirectory)/frontend'
    - task: CmdLine@2
      displayName: Frontend Lint
      inputs:
        script: |
          npm run lint
        workingDirectory: '$(Build.SourcesDirectory)/frontend'

    - task: CmdLine@2
      displayName: Frontend Format
      inputs:
        script: |
          npm run format
        workingDirectory: '$(Build.SourcesDirectory)/frontend'