version: "2"

services:
  frontend:
    build: ./frontend
    container_name: "Compose2Kube_frontend"
    volumes:
      - "./frontend:/home/node"
    ports:
      - 80:3000

  backend_py:
    build: ./backend-py
    container_name: "Compose2Kube_backend_py"
    volumes:
      - "./backend:/app"
    ports:
      - 5001:5000

  backend_js:
    build: ./backend
    container_name: "Compose2Kube_backend_js"
    volumes:
      - ".backend:/home/node"
    ports:
      - 5000:5000
