version: "2"

services:

  nginx:
    build: ./nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: "Compose2Kube_frontend"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: "Compose2Kube_backend"
