version: "2"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: "Compose2Kube_frontend"
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: "Compose2Kube_backend"
