version: "2"

services:
  frontend:
    build: ./frontend
    container_name: "Compose2Kube_frontend"
    volumes:
      - "./app:/home/node"
    ports:
      - 3000:3000
  backend:
    build: ./backend
    container_name: "Compose2Kube_backend"
    volumes:
      - "./backend:/app"
    ports:
      - 5000:5000
